# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
    #- uses: warrenbuckley/Setup-MSBuild@v1
    
    
    - name: Nugetrestore
      run: nuget restore TestApplication.sln
      
    #- name: MSBuild
     # #working-directory: BuildDeployProject
      #run:  msbuild .\TestApplication.sln
    
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: Build solution **\*.sln
      run:  msbuild  TestApplication.sln /p:OutputPath='.\ReleaseMN'

    #- uses: actions/checkout@v2
     # name: Checkout
     
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ReleaseMN
        path: TestApplication\ReleaseMN

  test:
    
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: ReleaseMN
      
        env:
          AZURE_WEBAPP_NAME: 'nikhilwebapp1'
          AZURE_WEBAPP_PACKAGE_PATH: ./ReleaseMN
          #AZURE_WEBAPP_PACKAGE_PATH: 'D:\a\TestApplication27June20\TestApplication27June20\ReleaseMN'
      
      - name: Hello world
        run: echo Env $AZURE_WEBAPP_PACKAGE_PATH 
    
      - name: Deploy Artifacts
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
