# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
    #- uses: nuget/setup-nuget@v1
    #- uses: warrenbuckley/Setup-MSBuild@v1
    
    #- name: Nugetrestore
     # run: nuget restore TestApplication.sln
    
    #- name: MSBuild
    #  working-directory: TestApplication
    #  run:  msbuild TestApplication.csproj
    
    #- uses: microsoft/setup-msbuild@v1.0.0
    #- name: Build solution **\*.sln
     # run: msbuild  TestApplication.sln /p:OutputPath='.\TestApplication27June20\ReleaseMN'
    - uses: actions/checkout@v2
      name: Checkout
     
    - run: 'Template/Temp1@master'
      name: Test
        
        
